apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: helloappjava
build:
  artifacts:
  - image: helloappjava
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes/deployment.yml
    - kubernetes/service.yml
portForward:
- resourceType: service
  resourceName: helloappjava
  port: 80      
