apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: helloappjava
  name: helloappjava
  namespace: helloapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloappjava
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: helloappjava
    spec:
      containers:
      - image: helloappjava
        name: helloappjava
        ports:
        - containerPort: 8080
        resources: {}
status: {}
