apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
images:
- name: helloappjava
  newName: registry.mylab.com/rsingh-lib/helloappjava
  newTag: b1.20220709.083031