apiVersion: v1
kind: Service
metadata:
  labels:
    app: helloappjava
  name: helloappjava
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloappjava
  type: LoadBalancer
