apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: helloappjava
  name: helloappjava
  namespace: helloapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: helloappjava
status:
  loadBalancer: {}
